english_levels_1 = [
"abbaba, bpbpbd, fkdspj, aman, rybyiw, fpopd, aosg, apple, banana, cherry, date, elderberry, fig, grape, honeydew, iceberg, jackfruit, kiwi, lemon, mango, nectarine, orange, papaya, quince, raspberry, strawberry, tangerine, umbrella, vanilla, watermelon, xigua, yuzu, zucchini, aardvark, baboon, capybara, dolphin, elephant, flamingo, giraffe, hippopotamus, iguana, jaguar, kangaroo, lemur, monkey, narwhal, octopus, penguin, queenfish, rhinoceros, seahorse, tortoise, unicorn, vulture, walrus, xenops, yak, zebra"
]

english_levels_2 = [
    "My name is Oksana. I am a prospective teacher of biology. Nature is my hobby. I know a lot about fruit and vegetables, and about their useful qualities. My friends say I am fond of diets, healthy food and healthy way of life. That's true. Food is an important part of our life; it may influence our mood and health. That's why I always eat the dishes I prepare myself and try to choose products, that are useful for my health.",
    "I live in a hostel, so I do not have much time to prepare my breakfast in the morning, as I share the kitchen with other students. But to cook oatmeal I need 5—10 minutes. In order to make it tastier, I usually add fruits to it. I also drink a glass of apple or orange juice in the morning. At about 12 o'clock I have my lunch. It is usually an apple, a banana or a glass of juice. Sometimes I eat vegetable salad or drink tea with pies.",
    "When I come home after classes I start preparing my dinner. It usually consists of vegetable soup for the first course, stewed fish with vegetables for the second one and stewed fruits or jelly for dessert. I do not have supper, as I do not want to overeat before going to bed. But sometimes I eat an apple or drink a glass of apple juice. I think, the food I choose is healthy and helps me to keep fit."
]
